# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
weight = 1
url = "https://github.com/yameizitd"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
weight = 2
url = "mailto:yameizitd@gmail.com"

[social.params]
icon = "brand-email"
